### ISSUE TITLE
When not approved, able to redirect to approvals page using url

### ISSUE THREAD

**Issue by Darren-lin** [mikeriepe/amplifytasselapp#61]
**Description:**

Able to change the url to /approvals and go to the page without being approved or admin

**Impact:**

Malicious users can approve or deny accounts when not admin

**Possible Solutions:**

Redirect before loading each page and check if the current user has admin status with useAuth()

**Comment by danielchandg** [comment]
Fixed https://github.com/mikeriepe/amplifytasselapp/pull/84
